site_name: Radiate
repo_url: http://github.com/pkalivas/radiate
repo_name: radiate

nav:
  - Home:
    - User Guide: index.md
    - Getting Started: source/installation.md
  - Genome:
    - source/genome/index.md
    - Ecosystem: source/genome/ecosystem.md
    - Codec: source/genome/codec.md
    - Example: source/genome/example.md
  - Parameters:
      - Selectors: 
          - source/selectors/index.md
          - Example: source/selectors/example.md
      - Alterers:
          - source/alters/index.md
          - Rate: source/alters/rate.md
          - Mutators: source/alters/mutators.md
          - Crossovers: source/alters/crossovers.md
          - Example: source/alters/example.md
      - Diversity: 
          - source/diversity/index.md
          - Distance: source/diversity/distance.md
          - Example: source/diversity/example.md
      - Executor: source/executors.md
      - Objectives: source/objectives.md
      - Fitness: source/fitness.md
      - Events: source/events.md
  - Engine:
    - source/engine/index.md
    - Metrics: source/engine/metrics.md
  - GP: 
    - source/gp/index.md
    - Ops: source/gp/op.md
    - Node: source/gp/node.md
    - Tree: source/gp/trees.md
    - Graph: source/gp/graph.md
    - Regression: source/gp/regression.md
  - Misc: 
    - source/misc/index.md
    - Randomness: source/misc/random.md
    - Problem API: source/misc/problem.md
    - Checkpointing: source/misc/checkpoint.md
    - UI: source/misc/ui.md
  - Examples: source/examples.md
  - Release Notes: source/releases.md

theme:
  favicon: assets/logo/radiate.ico
  logo: assets/logo/radiate.png
  name: material
  features:
    - navigation.tracking
    # - navigation.expand        # (leave OFF if you want collapsed-by-default)
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.indexes
    - content.tabs.link
    - content.code.copy
  language: en
  palette:
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: blue
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: deep-orange
      accent: light-green 

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - tables
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pkalivas/radiate
  generator: 
extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css  
