[package]
name = "xor-neat-backprop"
description = "XOR for the neat algorithm."
version = "1.0.0"
authors = ["pkalivas <peterkalivas@gmail.com>"]

[dependencies]
radiate={path="../../radiate"}
serde = "*"
serde_json="*"