[package]
name = "regression-graph"
version = "0.1.0"
edition = "2024"

[dependencies]
radiate = { workspace = true, features = ["gp", "serde", "pgm", "smallvec", "dashboard"] }
serde = { version = "1.0.224", features = ["derive"] }
serde_json = { version = "1.0.145" }
